name: "Terraform"

on: push

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      options: --entrypoint "/usr/bin/env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

